<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.1" os="" host="LAPTOP-5V88B96L"><DocLocation><![CDATA[C:\Users\kunda\OneDrive\Documents\test2\web]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[web]]></DName>
<Res><![CDATA[Res22]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:39]]></Time>
<TimeTick>1602691299</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:39]]></Time>
<TimeTick>1602691299</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:41]]></Time>
<TimeTick>1602691301</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:41]]></Time>
<TimeTick>1602691301</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="14" >
<Disp><![CDATA[agentName.Set]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[1960792328]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5f83b2d45fb9039bb58e"]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:42]]></Time>
<TimeTick>1602691302</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" >
<Disp><![CDATA[password.SetSecure]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[1952143984]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[OK]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfButton]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:43]]></Time>
<TimeTick>1602691303</TimeTick>
<HtmlStep rID="T11">
<HTML><![CDATA[<html>
<head>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8"/>
<base href=""/>
<link rel="stylesheet" href="Results.css"/>
</head>
<body bgcolor="#ffffff" leftmargin="20" marginwidth="20" topmargin="10" marginheight="10" vlink="#9966cc">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr><td height="1" class="bg_midblue"></td></tr>
	<tr><td height="30"><span class="hl1"> Standard Checkpoint "CheckOKButton": </span><span class="PassedHigh">Passed</span></td></tr>
	<tr><td height="2" class="bg_darkblue"></td></tr>
	<tr><td height="10"></td></tr>
	<tr><td><span class="text"><b>Date and Time:</b> 10/14/2020 - 12:01:43</span></td></tr>
		
	<tr><td height="15"></td></tr>
</table>
<!--Until here code from report media-->
<table border="0" cellpadding="0" cellspacing="0" width="100%" id=TABLE2><tr height="1"><td height="1" class="bg_gray_ccc"></td></tr><tr><td height="5"></td></tr></table><table>
	<tr><td height="30"><span class="hl2"> Details</span></td></tr><tr><td height="5"></td></tr>
</table>
<table border="0" cellpadding="3" cellspacing="1" width="100%" bgcolor="#666699">
	<tr>
		<td bgcolor="white">
		<table border="0" cellpadding="3" cellspacing="0" width="100%">
<tr><td  class="hl3">CheckOKButton Results&nbsp;</td></tr>
<tr><th colspan=2 height=1 class="bg_darkblue"></th></tr>
<TR>
				<td height=1 class="tablehl">Property Name&nbsp;&nbsp;</td>
				<td height=1 class="tablehl">Property Value&nbsp;&nbsp;</td>
</TR>
			<TR><th colspan=2 height=1 class="bg_gray_eee"></th></TR><tr><th colspan=2 height=1 class="bg_darkblue"></th></tr>
<TR>
				<TD class="Text" Title="">enabled&nbsp;</TD>
				<TD class="Text" Title="">True&nbsp;</TD>
</TR>
			<TR><th colspan=2 height=1 class="bg_gray_eee"></th></TR><TR>
				<TD class="Text" Title="">text&nbsp;</TD>
				<TD class="Text" Title="">OK&nbsp;</TD>
</TR>
			<TR><th colspan=2 height=1 class="bg_gray_eee"></th></TR>
		</table>
		</td>
	</tr>
</table>
</body></html>]]></HTML>
<TimeTick>1602691303</TimeTick>
<NodeArgs eType="Verification" icon="8" nRep="18" status="Passed" >
<Disp><![CDATA[Checkpoint "CheckOKButton"]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[1952099888]]></ASHilite>
</BtmPane>
</NodeArgs>
</HtmlStep>
<NodeArgs eType="Context" icon="8" nRep="17" status="Passed" >
<Disp><![CDATA[OK]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[1952099888]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:44]]></Time>
<TimeTick>1602691304</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" >
<Disp><![CDATA[OK.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[1952099888]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="13" status="Passed" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[265734]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="10/14/2020 - 12:01:36" eTime="10/14/2020 - 12:01:45" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T13">
<AName><![CDATA[FlightReservation]]></AName>
<AIter rID="T14" iterID="1" isCountable="False" >
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:45]]></Time>
<TimeTick>1602691305</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Denver"]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:46]]></Time>
<TimeTick>1602691306</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="26" >
<Disp><![CDATA[fromCity.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf2.xml]]></Path>
<ASHilite><![CDATA[2048068488]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:46]]></Time>
<TimeTick>1602691306</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="28" >
<Disp><![CDATA[toCity.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf3.xml]]></Path>
<ASHilite><![CDATA[2048070792]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["11/11/2020"]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:47]]></Time>
<TimeTick>1602691307</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="30" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf4.xml]]></Path>
<ASHilite><![CDATA[2048073240]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Class.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["First"]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:48]]></Time>
<TimeTick>1602691308</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="32" >
<Disp><![CDATA[Class.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf5.xml]]></Path>
<ASHilite><![CDATA[2048075400]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[numOfTickets.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["2"]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:49]]></Time>
<TimeTick>1602691309</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="34" >
<Disp><![CDATA[numOfTickets.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf6.xml]]></Path>
<ASHilite><![CDATA[2048074536]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:49]]></Time>
<TimeTick>1602691309</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="36" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf7.xml]]></Path>
<ASHilite><![CDATA[0]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA["1", "0"]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:50]]></Time>
<TimeTick>1602691310</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="38" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf8.xml]]></Path>
<ASHilite><![CDATA[1960790264]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:51]]></Time>
<TimeTick>1602691311</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="40" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf9.xml]]></Path>
<ASHilite><![CDATA[0]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Mary"]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:51]]></Time>
<TimeTick>1602691311</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="42" >
<Disp><![CDATA[passengerName.Set]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf10.xml]]></Path>
<ASHilite><![CDATA[1960794968]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:52]]></Time>
<TimeTick>1602691312</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="44" >
<Disp><![CDATA[ORDER.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf11.xml]]></Path>
<ASHilite><![CDATA[1960795160]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Order completed]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfObject]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:58]]></Time>
<TimeTick>1602691318</TimeTick>
<HtmlStep rID="T27">
<HTML><![CDATA[<html>
<head>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8"/>
<base href=""/>
<link rel="stylesheet" href="Results.css"/>
</head>
<body bgcolor="#ffffff" leftmargin="20" marginwidth="20" topmargin="10" marginheight="10" vlink="#9966cc">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr><td height="1" class="bg_midblue"></td></tr>
	<tr><td height="30"><span class="hl1"> Text Checkpoint "CheckOrderCompleted": </span><span class="PassedHigh">Passed</span></td></tr>
	<tr><td height="2" class="bg_darkblue"></td></tr>
	<tr><td height="10"></td></tr>
	<tr><td><span class="text"><b>Date and Time:</b> 10/14/2020 - 12:01:58</span></td></tr>
		
	<tr><td height="15"></td></tr>
</table>
<!--Until here code from report media-->
<table border="0" cellpadding="0" cellspacing="0" width="100%" id=TABLE2><tr height="1"><td height="1" class="bg_gray_ccc"></td></tr><tr><td height="5"></td></tr></table><table>
	<tr><td height="30"><span class="hl2"> Details</span></td></tr><tr><td height="5"></td></tr>
</table>
<span class="text"></span><span class="text">Text Checkpoint: captured </span><span  class="Passed">"completed"</span><span  class="text"><br>
</span><span  class="text">Match case: OFF<br>
</span><span  class="text">Exact match: OFF<br>
</span><span  class="text">Ignore spaces: ON</span></body></html>]]></HTML>
<TimeTick>1602691318</TimeTick>
<NodeArgs eType="Verification" icon="13" nRep="46" status="Passed" >
<Disp><![CDATA[Checkpoint "CheckOrderCompleted"]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf13.xml]]></Path>
<ASHilite><![CDATA[1961257616]]></ASHilite>
</BtmPane>
</NodeArgs>
</HtmlStep>
<NodeArgs eType="Context" icon="13" nRep="45" status="Passed" >
<Disp><![CDATA[Order completed]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf12.xml]]></Path>
<ASHilite><![CDATA[1961257616]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 12:01:59]]></Time>
<TimeTick>1602691319</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="48" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf14.xml]]></Path>
<ASHilite><![CDATA[0]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["SEARCH ORDER"]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:00]]></Time>
<TimeTick>1602691320</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="50" >
<Disp><![CDATA[WpfTabStrip.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf15.xml]]></Path>
<ASHilite><![CDATA[1965874200]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[byNameOrDateRadio.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:00]]></Time>
<TimeTick>1602691320</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="52" >
<Disp><![CDATA[byNameOrDateRadio.Set]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf16.xml]]></Path>
<ASHilite><![CDATA[1964709464]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[byNameWatermark.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Mary"]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:01]]></Time>
<TimeTick>1602691321</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="54" >
<Disp><![CDATA[byNameWatermark.Set]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf17.xml]]></Path>
<ASHilite><![CDATA[1965874632]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[byDatePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["11/11/2020"]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:02]]></Time>
<TimeTick>1602691322</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="56" >
<Disp><![CDATA[byDatePicker.SetDate]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf18.xml]]></Path>
<ASHilite><![CDATA[1965875880]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:02]]></Time>
<TimeTick>1602691322</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="58" >
<Disp><![CDATA[SEARCH.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf19.xml]]></Path>
<ASHilite><![CDATA[0]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[ordersDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 0]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:03]]></Time>
<TimeTick>1602691323</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="60" >
<Disp><![CDATA[ordersDataGrid.SelectCell]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf20.xml]]></Path>
<ASHilite><![CDATA[2124309728]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[SELECT ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:04]]></Time>
<TimeTick>1602691324</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="62" >
<Disp><![CDATA[SELECT ORDER.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf21.xml]]></Path>
<ASHilite><![CDATA[0]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:06]]></Time>
<TimeTick>1602691326</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="64" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf22.xml]]></Path>
<ASHilite><![CDATA[0]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="25" status="Passed" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf1.xml]]></Path>
<ASHilite><![CDATA[593398]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="23" status="Passed" >
<Disp><![CDATA[FlightReservation Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</AIter>
<AIter rID="T37" iterID="2" isCountable="False" >
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:07]]></Time>
<TimeTick>1602691327</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:08]]></Time>
<TimeTick>1602691328</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="69" >
<Disp><![CDATA[fromCity.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf2.xml]]></Path>
<ASHilite><![CDATA[2048075112]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Frankfurt"]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:09]]></Time>
<TimeTick>1602691329</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="71" >
<Disp><![CDATA[toCity.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf3.xml]]></Path>
<ASHilite><![CDATA[2048074968]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["11/12/2020"]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:09]]></Time>
<TimeTick>1602691329</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="73" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf4.xml]]></Path>
<ASHilite><![CDATA[2048075832]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Class.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Business"]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:10]]></Time>
<TimeTick>1602691330</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="75" >
<Disp><![CDATA[Class.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf5.xml]]></Path>
<ASHilite><![CDATA[2048075544]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[numOfTickets.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:11]]></Time>
<TimeTick>1602691331</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="77" >
<Disp><![CDATA[numOfTickets.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf6.xml]]></Path>
<ASHilite><![CDATA[2048075592]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:12]]></Time>
<TimeTick>1602691332</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="79" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf7.xml]]></Path>
<ASHilite><![CDATA[0]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA["3", "0"]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:12]]></Time>
<TimeTick>1602691332</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="81" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf8.xml]]></Path>
<ASHilite><![CDATA[2048077704]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:13]]></Time>
<TimeTick>1602691333</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="83" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf9.xml]]></Path>
<ASHilite><![CDATA[0]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Regina"]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:14]]></Time>
<TimeTick>1602691334</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="85" >
<Disp><![CDATA[passengerName.Set]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf10.xml]]></Path>
<ASHilite><![CDATA[1965874920]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:15]]></Time>
<TimeTick>1602691335</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="87" >
<Disp><![CDATA[ORDER.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf11.xml]]></Path>
<ASHilite><![CDATA[2124310448]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Order completed]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfObject]]></Details>
<Time><![CDATA[10/14/2020 - 12:02:19]]></Time>
<TimeTick>1602691339</TimeTick>
<HtmlStep rID="T50">
<HTML><![CDATA[<html>
<head>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8"/>
<base href=""/>
<link rel="stylesheet" href="Results.css"/>
</head>
<body bgcolor="#ffffff" leftmargin="20" marginwidth="20" topmargin="10" marginheight="10" vlink="#9966cc">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr><td height="1" class="bg_midblue"></td></tr>
	<tr><td height="30"><span class="hl1"> Text Checkpoint "CheckOrderCompleted": </span><span class="PassedHigh">Passed</span></td></tr>
	<tr><td height="2" class="bg_darkblue"></td></tr>
	<tr><td height="10"></td></tr>
	<tr><td><span class="text"><b>Date and Time:</b> 10/14/2020 - 12:02:20</span></td></tr>
		
	<tr><td height="15"></td></tr>
</table>
<!--Until here code from report media-->
<table border="0" cellpadding="0" cellspacing="0" width="100%" id=TABLE2><tr height="1"><td height="1" class="bg_gray_ccc"></td></tr><tr><td height="5"></td></tr></table><table>