<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.1" os="" host="LAPTOP-5V88B96L"><DocLocation><![CDATA[C:\Users\kunda\OneDrive\Documents\test\tt]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[tt]]></DName>
<Res><![CDATA[Res6]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:36]]></Time>
<TimeTick>1602682656</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:36]]></Time>
<TimeTick>1602682656</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Login" SourceLine="1" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Login" SourceLine="1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:38]]></Time>
<TimeTick>1602682658</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:38]]></Time>
<TimeTick>1602682658</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="14" Source="Login" SourceLine="13" >
<Disp><![CDATA[agentName.Set]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf14.xml]]></Path>
<ASHilite><![CDATA[2085032152]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5f83b2d45fb9039bb58e"]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:39]]></Time>
<TimeTick>1602682659</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" Source="Login" SourceLine="14" >
<Disp><![CDATA[password.SetSecure]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf15.xml]]></Path>
<ASHilite><![CDATA[2085032872]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[OK]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfButton]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:39]]></Time>
<TimeTick>1602682659</TimeTick>
<HtmlStep rID="T11">
<HTML><![CDATA[<html>
<head>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8"/>
<base href=""/>
<link rel="stylesheet" href="Results.css"/>
</head>
<body bgcolor="#ffffff" leftmargin="20" marginwidth="20" topmargin="10" marginheight="10" vlink="#9966cc">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr><td height="1" class="bg_midblue"></td></tr>
	<tr><td height="30"><span class="hl1"> Standard Checkpoint "CheckOKButton": </span><span class="PassedHigh">Passed</span></td></tr>
	<tr><td height="2" class="bg_darkblue"></td></tr>
	<tr><td height="10"></td></tr>
	<tr><td><span class="text"><b>Date and Time:</b> 10/14/2020 - 9:37:40</span></td></tr>
		
	<tr><td height="15"></td></tr>
</table>
<!--Until here code from report media-->
<table border="0" cellpadding="0" cellspacing="0" width="100%" id=TABLE2><tr height="1"><td height="1" class="bg_gray_ccc"></td></tr><tr><td height="5"></td></tr></table><table>
	<tr><td height="30"><span class="hl2"> Details</span></td></tr><tr><td height="5"></td></tr>
</table>
<table border="0" cellpadding="3" cellspacing="1" width="100%" bgcolor="#666699">
	<tr>
		<td bgcolor="white">
		<table border="0" cellpadding="3" cellspacing="0" width="100%">
<tr><td  class="hl3">CheckOKButton Results&nbsp;</td></tr>
<tr><th colspan=2 height=1 class="bg_darkblue"></th></tr>
<TR>
				<td height=1 class="tablehl">Property Name&nbsp;&nbsp;</td>
				<td height=1 class="tablehl">Property Value&nbsp;&nbsp;</td>
</TR>
			<TR><th colspan=2 height=1 class="bg_gray_eee"></th></TR><tr><th colspan=2 height=1 class="bg_darkblue"></th></tr>
<TR>
				<TD class="Text" Title="">enabled&nbsp;</TD>
				<TD class="Text" Title="">True&nbsp;</TD>
</TR>
			<TR><th colspan=2 height=1 class="bg_gray_eee"></th></TR><TR>
				<TD class="Text" Title="">text&nbsp;</TD>
				<TD class="Text" Title="">OK&nbsp;</TD>
</TR>
			<TR><th colspan=2 height=1 class="bg_gray_eee"></th></TR>
		</table>
		</td>
	</tr>
</table>
</body></html>]]></HTML>
<TimeTick>1602682660</TimeTick>
<NodeArgs eType="Verification" icon="8" nRep="18" status="Passed" Source="Login" SourceLine="15" >
<Disp><![CDATA[Checkpoint "CheckOKButton"]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf17.xml]]></Path>
<ASHilite><![CDATA[2050109096]]></ASHilite>
</BtmPane>
</NodeArgs>
</HtmlStep>
<NodeArgs eType="Context" icon="8" nRep="17" status="Passed" Source="Login" SourceLine="15" >
<Disp><![CDATA[OK]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf16.xml]]></Path>
<ASHilite><![CDATA[2050109096]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:40]]></Time>
<TimeTick>1602682660</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" Source="Login" SourceLine="16" >
<Disp><![CDATA[OK.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf18.xml]]></Path>
<ASHilite><![CDATA[2050109096]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="13" status="Passed" Source="Login" SourceLine="13" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf13.xml]]></Path>
<ASHilite><![CDATA[265650]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="10/14/2020 - 9:37:36" eTime="10/14/2020 - 9:37:40" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T13">
<AName><![CDATA[FlightReservation]]></AName>
<AIter rID="T14" iterID="1" isCountable="False" >
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:41]]></Time>
<TimeTick>1602682661</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Denver"]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:41]]></Time>
<TimeTick>1602682661</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="26" Source="FlightReservation" SourceLine="0" >
<Disp><![CDATA[fromCity.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf35.xml]]></Path>
<ASHilite><![CDATA[2085033544]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:42]]></Time>
<TimeTick>1602682662</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="28" Source="FlightReservation" SourceLine="1" >
<Disp><![CDATA[toCity.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf36.xml]]></Path>
<ASHilite><![CDATA[2085035800]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["11/11/2020"]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:42]]></Time>
<TimeTick>1602682662</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="30" Source="FlightReservation" SourceLine="2" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf37.xml]]></Path>
<ASHilite><![CDATA[2085035272]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Class.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["First"]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:43]]></Time>
<TimeTick>1602682663</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="32" Source="FlightReservation" SourceLine="3" >
<Disp><![CDATA[Class.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf38.xml]]></Path>
<ASHilite><![CDATA[2085035752]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[numOfTickets.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["2"]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:44]]></Time>
<TimeTick>1602682664</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="34" Source="FlightReservation" SourceLine="4" >
<Disp><![CDATA[numOfTickets.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf39.xml]]></Path>
<ASHilite><![CDATA[2085036904]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:45]]></Time>
<TimeTick>1602682665</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="36" Source="FlightReservation" SourceLine="5" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf40.xml]]></Path>
<ASHilite><![CDATA[0]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA["1", "0"]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:45]]></Time>
<TimeTick>1602682665</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="38" Source="FlightReservation" SourceLine="7" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf41.xml]]></Path>
<ASHilite><![CDATA[2085037720]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:45]]></Time>
<TimeTick>1602682665</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="40" Source="FlightReservation" SourceLine="9" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf42.xml]]></Path>
<ASHilite><![CDATA[0]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Mary"]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:46]]></Time>
<TimeTick>1602682666</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="42" Source="FlightReservation" SourceLine="11" >
<Disp><![CDATA[passengerName.Set]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf43.xml]]></Path>
<ASHilite><![CDATA[2085040024]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:47]]></Time>
<TimeTick>1602682667</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="44" Source="FlightReservation" SourceLine="13" >
<Disp><![CDATA[ORDER.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf44.xml]]></Path>
<ASHilite><![CDATA[2085041464]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Order completed]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfObject]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:51]]></Time>
<TimeTick>1602682671</TimeTick>
<HtmlStep rID="T27">
<HTML><![CDATA[<html>
<head>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8"/>
<base href=""/>
<link rel="stylesheet" href="Results.css"/>
</head>
<body bgcolor="#ffffff" leftmargin="20" marginwidth="20" topmargin="10" marginheight="10" vlink="#9966cc">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr><td height="1" class="bg_midblue"></td></tr>
	<tr><td height="30"><span class="hl1"> Text Checkpoint "CheckOrderCompleted": </span><span class="PassedHigh">Passed</span></td></tr>
	<tr><td height="2" class="bg_darkblue"></td></tr>
	<tr><td height="10"></td></tr>
	<tr><td><span class="text"><b>Date and Time:</b> 10/14/2020 - 9:37:51</span></td></tr>
		
	<tr><td height="15"></td></tr>
</table>
<!--Until here code from report media-->
<table border="0" cellpadding="0" cellspacing="0" width="100%" id=TABLE2><tr height="1"><td height="1" class="bg_gray_ccc"></td></tr><tr><td height="5"></td></tr></table><table>
	<tr><td height="30"><span class="hl2"> Details</span></td></tr><tr><td height="5"></td></tr>
</table>
<span class="text"></span><span class="text">Text Checkpoint: captured </span><span  class="Passed">"completed"</span><span  class="text"><br>
</span><span  class="text">Match case: OFF<br>
</span><span  class="text">Exact match: OFF<br>
</span><span  class="text">Ignore spaces: ON</span></body></html>]]></HTML>
<TimeTick>1602682671</TimeTick>
<NodeArgs eType="Verification" icon="13" nRep="46" status="Passed" Source="FlightReservation" SourceLine="15" >
<Disp><![CDATA[Checkpoint "CheckOrderCompleted"]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf46.xml]]></Path>
<ASHilite><![CDATA[2031691048]]></ASHilite>
</BtmPane>
</NodeArgs>
</HtmlStep>
<NodeArgs eType="Context" icon="13" nRep="45" status="Passed" Source="FlightReservation" SourceLine="15" >
<Disp><![CDATA[Order completed]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf45.xml]]></Path>
<ASHilite><![CDATA[2031691048]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:52]]></Time>
<TimeTick>1602682672</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="48" Source="FlightReservation" SourceLine="16" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf47.xml]]></Path>
<ASHilite><![CDATA[0]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["SEARCH ORDER"]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:52]]></Time>
<TimeTick>1602682672</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="50" Source="FlightReservation" SourceLine="17" >
<Disp><![CDATA[WpfTabStrip.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf48.xml]]></Path>
<ASHilite><![CDATA[2034773048]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[byNameOrDateRadio.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:53]]></Time>
<TimeTick>1602682673</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="52" Source="FlightReservation" SourceLine="18" >
<Disp><![CDATA[byNameOrDateRadio.Set]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf49.xml]]></Path>
<ASHilite><![CDATA[2045113056]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[byNameWatermark.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Mary"]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:53]]></Time>
<TimeTick>1602682673</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="54" Source="FlightReservation" SourceLine="19" >
<Disp><![CDATA[byNameWatermark.Set]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf50.xml]]></Path>
<ASHilite><![CDATA[1904728880]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[byDatePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["11/11/2020"]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:54]]></Time>
<TimeTick>1602682674</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="56" Source="FlightReservation" SourceLine="20" >
<Disp><![CDATA[byDatePicker.SetDate]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf51.xml]]></Path>
<ASHilite><![CDATA[1904727776]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:55]]></Time>
<TimeTick>1602682675</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="58" Source="FlightReservation" SourceLine="21" >
<Disp><![CDATA[SEARCH.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf52.xml]]></Path>
<ASHilite><![CDATA[0]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[ordersDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 0]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:55]]></Time>
<TimeTick>1602682675</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="60" Source="FlightReservation" SourceLine="22" >
<Disp><![CDATA[ordersDataGrid.SelectCell]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf53.xml]]></Path>
<ASHilite><![CDATA[2050108664]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[SELECT ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:56]]></Time>
<TimeTick>1602682676</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="62" Source="FlightReservation" SourceLine="23" >
<Disp><![CDATA[SELECT ORDER.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf54.xml]]></Path>
<ASHilite><![CDATA[0]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:56]]></Time>
<TimeTick>1602682676</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="64" Source="FlightReservation" SourceLine="24" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf55.xml]]></Path>
<ASHilite><![CDATA[0]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="25" status="Passed" Source="FlightReservation" SourceLine="0" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row1\ssf34.xml]]></Path>
<ASHilite><![CDATA[1445356]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="23" status="Passed" >
<Disp><![CDATA[FlightReservation Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</AIter>
<AIter rID="T37" iterID="2" isCountable="False" >
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:57]]></Time>
<TimeTick>1602682677</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:57]]></Time>
<TimeTick>1602682677</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="69" Source="FlightReservation" SourceLine="0" >
<Disp><![CDATA[fromCity.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf24.xml]]></Path>
<ASHilite><![CDATA[2050081640]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Frankfurt"]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:58]]></Time>
<TimeTick>1602682678</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="71" Source="FlightReservation" SourceLine="1" >
<Disp><![CDATA[toCity.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf25.xml]]></Path>
<ASHilite><![CDATA[2040904056]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["11/12/2020"]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:59]]></Time>
<TimeTick>1602682679</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="73" Source="FlightReservation" SourceLine="2" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf26.xml]]></Path>
<ASHilite><![CDATA[1904738384]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Class.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Business"]]></Details>
<Time><![CDATA[10/14/2020 - 9:37:59]]></Time>
<TimeTick>1602682679</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="75" Source="FlightReservation" SourceLine="3" >
<Disp><![CDATA[Class.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf27.xml]]></Path>
<ASHilite><![CDATA[1904736992]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[numOfTickets.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[10/14/2020 - 9:38:00]]></Time>
<TimeTick>1602682680</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="77" Source="FlightReservation" SourceLine="4" >
<Disp><![CDATA[numOfTickets.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf28.xml]]></Path>
<ASHilite><![CDATA[2050082792]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 9:38:01]]></Time>
<TimeTick>1602682681</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="79" Source="FlightReservation" SourceLine="5" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf29.xml]]></Path>
<ASHilite><![CDATA[0]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA["3", "0"]]></Details>
<Time><![CDATA[10/14/2020 - 9:38:01]]></Time>
<TimeTick>1602682681</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="81" Source="FlightReservation" SourceLine="7" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf30.xml]]></Path>
<ASHilite><![CDATA[1904738960]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/14/2020 - 9:38:02]]></Time>
<TimeTick>1602682682</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="83" Source="FlightReservation" SourceLine="9" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf31.xml]]></Path>
<ASHilite><![CDATA[0]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Regina"]]></Details>
<Time><![CDATA[10/14/2020 - 9:38:02]]></Time>
<TimeTick>1602682682</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="85" Source="FlightReservation" SourceLine="11" >
<Disp><![CDATA[passengerName.Set]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row2\ssf32.xml]]></Path>
<ASHilite><![CDATA[2040906360]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>